config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'home#index'
  
  resources :todo_lists
  resources :task
  resources :home, only: [:index]
  resources :stopwatch, only: [:create, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/stopwatch.rb
class Stopwatch < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @todo_lists = TodoList.all
    
    if current_user.present?
      @stopwatch = Stopwatch.find_by(user_id: current_user.id)  

      unless @stopwatch.present?  
        @stopwatch = Stopwatch.new(work_cyle: 25, fast_pause: 5, long_pause: 30, has_sound_on_terminate: true)
      end
    end  
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  
    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end
  
    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :avatar)
    end
end

app/controllers/stopwatch_controller.rb
class StopwatchController < ApplicationController
  before_action :set_stopwatch, only: [:update, :show]

  def create
    @stopwatch = Stopwatch.new(stopwatch_params)

    respond_to do |format|
      if @stopwatch.save
        format.json { render :show, status: :created, location: @stopwatch }
      else
        format.json { render json: @stopwatch.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @stopwatch.update(stopwatch_params)
        format.json { render :show, status: :ok, location: @stopwatch_params }
      else
        format.json { render json: @stopwatch_params.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private
    def set_stopwatch
      @stopwatch = Stopwatch.find(params[:id])
    end

    def stopwatch_params
      params.require(:stopwatch).permit(:work_cyle, :fast_pause, :long_pause, :has_sound_on_terminate).merge(user_id: current_user.id)
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]
      
    # GET /tasks
    # GET /tasks.json
    def index
        @tasks = Task.all
    end
      
    # GET /tasks/1
    # GET /tasks/1.json
    def show
    end
      
    # GET /tasks/new
    def new
        @task = Task.new
    end
      
    # GET /tasks/1/edit
    def edit
    end
      
    # POST /tasks
    # POST /tasks.json
    def create
        @task = Task.new(task_params)
      
        respond_to do |format|
            if @task.save
              format.html { redirect_to @task, notice: 'Task was successfully created.' }
              format.json { render :show, status: :created, location: @task }
            else
              format.html { render :new }
              format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
    end
      
    # PATCH/PUT /tasks/1
    # PATCH/PUT /tasks/1.json
    def update
        respond_to do |format|
            if @task.update(task_params)
              format.html { redirect_to @task, notice: 'Todo list was successfully updated.' }
              format.json { render :show, status: :ok, location: @task }
            else
              format.html { render :edit }
              format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
    end
      
    # DELETE /tasks/1
    # DELETE /tasks/1.json
    def destroy
        @task.destroy
        respond_to do |format|
            format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
      
    private
        # Use callbacks to share common setup or constraints between actions.
        def set_task
            @task = Task.find(params[:id])
        end
      
        # Never trust parameters from the scary internet, only allow the white list through.
        def task_params
            params.require(:task).permit(:title, :description)
        end
    #end
#end    
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to root_path, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to root_path, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/stopwatch_helper.rb
module StopwatchHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/home/index.html.erb
<%= render "stopwatch/index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PomodoroClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <header>
      <%= render "shared/navbar" %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="page-footer teal accent-4">
  <div class="container">
    <div class="copyright ">
      <b>Criado no WeekCode do <a class="copyright-link" href="https://onebitcode.com/">OneBitCode</a>
      </b>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav teal accent-4">
    <div class="nav-wrapper col s12">
      <a href="/" class="brand-logo">
        <%= image_tag("logo.png", class: "logo-img") %>

        <span class="logo-title">
          Pomodoro Clone
        </span>
      </a>

      <a href="#" data-target="side-bar" class="sidenav-trigger"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <% if current_user %>
          <li><a href="/users/edit">Perfil</a></li>
          <li>  <%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><a href="/users/sign_in">Entrar</a></li>
          <li><a href="/users/sign_up">Criar Conta</a></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

<ul class="sidenav" id="side-bar">
  <% if current_user %>
    <li><a href="/users/edit">Perfil</a></li>
    <li><div class="divider"></div></li>
    <li>  <%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
    <li><a href="/users/sign_in">Entrar</a></li>
    <li><div class="divider"></div></li>
    <li><a href="/users/sign_up">Criar Conta</a></li>
    <li><div class="divider"></div></li>
  <% end %>
</ul>

app/views/stopwatch/_index.html.erb
<div class="row">
  <div class="card teal accent-4">
    <div class="card-content white-text">
      <% if current_user %>
        <span class="card-title pomodoro-title">
          #1 <%= image_tag("logo.png", class: "logo-img") %>
          <button class="btn waves-effect waves-light right edit-settings"><i class="material-icons ">settings</i></button>
        </span>  
      <% end %>
      <div class="timer">00:00:00</div>
    </div>
    <div class="card-action">
      <button id="btnStart" class="btn waves-effect waves-light">Start<i class="material-icons left">play_circle_outline</i></button>
      <button id="btnPause" class="btn waves-effect waves-light">Pause<i class="material-icons left">pause_circle_outline</i></button>
      <button id="btnStop" class="btn waves-effect waves-light">Stop<i class="material-icons left">stop_circle_outline</i></button>
      <button id="btnLongPause" class="btn waves-effect waves-light right">Long Pause<i class="material-icons left">play_circle_outline</i></button>
      <button id="btnFastPause" class="btn waves-effect waves-light right">Fast Pause<i class="material-icons left">play_circle_outline</i></button>
    </div>
  </div>
  <div class="card teal accent-4">
    <div class="card-content white-text">
      <span class="card-title">Lista de Tarefas</span>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @todo_lists.each do |todo_list| %>
            <tr>
              <td><%= todo_list.title %></td>
              <td><%= todo_list.description %></td>
              <td><%= link_to 'Show', todo_list, class: 'btn' %></td>
              <td><%= link_to 'Edit', edit_todo_list_path(todo_list), class: 'btn' %></td>
              <td><%= link_to 'Destroy', todo_list, class: 'btn', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <button class="btn"><%= link_to 'Nova Lista de Tarefas', new_todo_list_path, class: 'white-text' %></button>
    </div>
  </div>
</div>

<% if current_user %>
  <%= render "stopwatch/settings" %>
<% end %>

app/views/stopwatch/_settings.html.erb
<div id="pomodoro_settings" class="modal">
  <div class="modal-content red lighten-5">
    <div class="row">
      <%= form_for @stopwatch, url: { controller: "stopwatch",  action: "create" }, html: { class: "col s12 change-settings" } do |f| %>
        <div class="row">
          <div class="col s12">
            <h4>Pomodoro Settings</h4>
          </div>
          <%= hidden_field(:stopwatch, :id) %>
          <div class="input-field col s12">
            <%= number_field(:stopwatch, :work_cyle, max: 59) %>
            <%= label_tag(:work_cyle, "Work Cycle (in minutes)") %>
          </div>
          <div class="input-field col s12">
            <%= number_field(:stopwatch, :fast_pause, max: 59) %>
            <%= label_tag(:fast_pause, "Fast Pause (in minutes)") %>
          </div>
          <div class="input-field col s12">
            <%= number_field(:stopwatch, :long_pause, max: 59) %>
            <%= label_tag(:long_pause, "Long Pause (in minutes)") %>
          </div>
          <div class="input-field col s2 switch">
            <label>
              Off
              <%= check_box_tag :has_sound_on_terminate, "", @stopwatch.has_sound_on_terminate %>
              <span class="lever"></span>
              On
            </label>            
          </div>
          <div class="input-field col s4 switch">
            <label>Play sound on terminate</label>
          </div>
          <br>
          <%= submit_tag("Save", class: "btn right") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/task/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title %>
  </div>

  <div class="field">
    <%= form.label :finished_at %>
    <%= form.text_area :finished_at, id: :task_finished_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', task_path %>

app/views/task/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Finished_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/task/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', task_path %>

app/views/task/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', task_path %>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :todo_list_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :todo_list_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/new.html.erb
<h1>Criar nova Lista</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', root_path %>

app/views/todo_lists/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', root_path %>